import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#10141a",
        "surface-dim": "#10141a",
        "surface-bright": "#353940",
        "surface-container-lowest": "#0a0e14",
        "surface-container-low": "#181c22",
        "surface-container": "#1c2026",
        "surface-container-high": "#262a31",
        "surface-container-highest": "#31353c",
        "on-surface": "#dfe2eb",
        "on-surface-variant": "#bdc8d1",
        "inverse-surface": "#dfe2eb",
        "inverse-on-surface": "#2d3137",
        outline: "#87929a",
        "outline-variant": "#3e484f",
        "surface-tint": "#7bd0ff",
        primary: "#8ed5ff",
        "on-primary": "#00354a",
        "primary-container": "#38bdf8",
        "on-primary-container": "#004965",
        "inverse-primary": "#00668a",
        secondary: "#bcc7de",
        "on-secondary": "#263143",
        "secondary-container": "#3e495d",
        "on-secondary-container": "#aeb9d0",
        tertiary: "#ffc176",
        "on-tertiary": "#472a00",
        "tertiary-container": "#f1a02b",
        "on-tertiary-container": "#613b00",
        error: "#f85149",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        background: "#10141a",
        "on-background": "#dfe2eb",
        "surface-variant": "#31353c",
        "editor-bg": "#0d1117",
        "panel-border": "#30363d",
        "text-high-contrast": "#f0f6fc",
        "text-muted": "#8b949e",
        success: "#238636",
        warning: "#d29922",
        "note-badge": "#79c0ff",
        "why-badge": "#d2a8ff",
        "complexity-badge": "#ffa657",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600", letterSpacing: "-0.02em" }],
        "headline-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "code-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "code-md": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "code-sm": ["11px", { lineHeight: "16px", fontWeight: "500" }],
        "label-caps": ["10px", { lineHeight: "12px", fontWeight: "700", letterSpacing: "0.05em" }],
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-margin": "1rem",
        gutter: "1px",
        "panel-padding": "1.25rem",
        "stack-gap": "0.75rem",
      },
    },
  },
  plugins: [],
};

export default config;
